name: Flutter CI/CD

on:
  push:
    branches: [master]

jobs:
  build_macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter config --enable-macos-desktop
      - run: flutter pub get
      - run: flutter build macos --enable-experiment=non-nullable --no-sound-null-safety
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: macos-build
          path: ./build/macos/Build/Products/Release/

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows --enable-experiment=non-nullable --no-sound-null-safety
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: windows-build
          path: build\windows\runner\Release

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter config --enable-linux-desktop
      - run: flutter pub get
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev libblkid-dev liblzma-dev
      - run: flutter build linux --enable-experiment=non-nullable --no-sound-null-safety
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux-build
          path: ./build/linux/release

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "dev"
      - run: flutter pub get
      - run: flutter build apk --enable-experiment=non-nullable --no-sound-null-safety
      - name: Upload build artifact
        uses: actions/upload-artifact@v1
        with:
          name: android-build
          path: ./build/app/outputs/flutter-apk/app-release.apk